### ISSUE TITLE
Do not rely on __str__ to get proxy info

### ISSUE THREAD

**Issue by Esequiel378** [FaHoLo/Avito_parser#1]
https://github.com/FaHoLo/Avito_parser/blob/95ad1b8dc2c6de0b13c8924597b8669e33f93560/Bot/utils.py#L101

Hello! Im the creator of proxy_randomizer, eventually i come across your project, amazin btw, the issue is that your are using __str__/str() to get the proxy info, and that a risky move, since that method could change in the future; instead you can use [get_proxy()](https://github.com/Esequiel378/proxy_randomizer/blob/fa3d33f9d46544bd293148640d0f987be9a0e3f8/proxy_randomizer/proxy.py#L139) method inside Proxy class

The code will be like this

```Python
def get_random_proxy() -> str:
    """Get proxy from _registered_providers (exclude anonymity and country info)."""
    if not _registered_providers:
        parse_providers()

    proxy = _registered_providers.get_random_proxy()

    return proxy.get_proxy()
```

This way you can be sure you code wont break

**Comment by FaHoLo** [comment]
Hello, Esequel! Thanks a lot for your attention and great advice! I have no idea, why I didn't find this method right away.
I fixed this issue in commit: https://github.com/FaHoLo/Avito_parser/commit/afdf97551fac6f731d389ff96340d27f865bfe35
Thanks for your awesome proxy_randomizer library!
